#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StateTask

#include "Basic.hpp"

#include "BP_StateTask_classes.hpp"
#include "BP_StateTask_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_StateTask.BP_StateTask_C.Should Snap State Sequence
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FStateTreeTransitionResult&Transition                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// bool*                                   Snap_State_Sequence                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_StateTask_C::Should_Snap_State_Sequence(const struct FStateTreeTransitionResult& Transition, bool* Snap_State_Sequence)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StateTask_C", "Should Snap State Sequence");

	Params::BP_StateTask_C_Should_Snap_State_Sequence Parms{};

	Parms.Transition = std::move(Transition);

	UObject::ProcessEvent(Func, &Parms);

	if (Snap_State_Sequence != nullptr)
		*Snap_State_Sequence = Parms.Snap_State_Sequence;
}


// Function BP_StateTask.BP_StateTask_C.ReceiveLatentTick
// (Event, Public, BlueprintEvent)
// Parameters:
// const float                             DeltaTime_ReceiveLatentTick                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_StateTask_C::ReceiveLatentTick(const float DeltaTime_ReceiveLatentTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StateTask_C", "ReceiveLatentTick");

	Params::BP_StateTask_C_ReceiveLatentTick Parms{};

	Parms.DeltaTime_ReceiveLatentTick = DeltaTime_ReceiveLatentTick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StateTask.BP_StateTask_C.ReceiveLatentEnterState
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FStateTreeTransitionResult&Transition_ReceiveLatentEnterState                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_StateTask_C::ReceiveLatentEnterState(const struct FStateTreeTransitionResult& Transition_ReceiveLatentEnterState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StateTask_C", "ReceiveLatentEnterState");

	Params::BP_StateTask_C_ReceiveLatentEnterState Parms{};

	Parms.Transition_ReceiveLatentEnterState = std::move(Transition_ReceiveLatentEnterState);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StateTask.BP_StateTask_C.Process State
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FStateTransitionInfo&      Current_State                                          (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_StateTask_C::Process_State(const struct FStateTransitionInfo& Current_State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StateTask_C", "Process State");

	Params::BP_StateTask_C_Process_State Parms{};

	Parms.Current_State = std::move(Current_State);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StateTask.BP_StateTask_C.ExecuteUbergraph_BP_StateTask
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_StateTask_C::ExecuteUbergraph_BP_StateTask(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StateTask_C", "ExecuteUbergraph_BP_StateTask");

	Params::BP_StateTask_C_ExecuteUbergraph_BP_StateTask Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StateTask.BP_StateTask_C.Convert Scene List
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<struct FSoftWorldReference>&     Scenes                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<TSoftObjectPtr<class UWorld>>*   Scenes_to_Ignore                                       (Parm, OutParm)

void UBP_StateTask_C::Convert_Scene_List(TArray<struct FSoftWorldReference>& Scenes, TArray<TSoftObjectPtr<class UWorld>>* Scenes_to_Ignore)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StateTask_C", "Convert Scene List");

	Params::BP_StateTask_C_Convert_Scene_List Parms{};

	Parms.Scenes = std::move(Scenes);

	UObject::ProcessEvent(Func, &Parms);

	Scenes = std::move(Parms.Scenes);

	if (Scenes_to_Ignore != nullptr)
		*Scenes_to_Ignore = std::move(Parms.Scenes_to_Ignore);
}


// Function BP_StateTask.BP_StateTask_C.Conditionally Finish Task
// (BlueprintCallable, BlueprintEvent)

void UBP_StateTask_C::Conditionally_Finish_Task()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StateTask_C", "Conditionally Finish Task");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
