#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SubLayerModifier

#include "Basic.hpp"

#include "ActorModifierCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_SubLayerModifier.BP_SubLayerModifier_C.OnModifierSetupEvent
// 0x07C0 (0x07C0 - 0x0000)
struct BP_SubLayerModifier_C_OnModifierSetupEvent final
{
public:
	struct FActorModifierCoreMetadata             InMetaData_OnModifierSetupEvent;                   // 0x0000(0x01F0)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FActorModifierCoreMetadata             OutMetadata_OnModifierSetupEvent;                  // 0x01F0(0x01F0)(Parm, OutParm)
	struct FActorModifierCoreMetadata             CallFunc_SetModifierMetadataName_ReturnValue;      // 0x03E0(0x01F0)()
	struct FActorModifierCoreMetadata             CallFunc_SetModifierMetadataCategory_ReturnValue;  // 0x05D0(0x01F0)()
};
DUMPER7_ASSERTS_BP_SubLayerModifier_C_OnModifierSetupEvent;

// Function BP_SubLayerModifier.BP_SubLayerModifier_C.OnModifierApplyEvent
// 0x0020 (0x0020 - 0x0000)
struct BP_SubLayerModifier_C_OnModifierApplyEvent final
{
public:
	class AActor*                                 InTargetActor_OnModifierApplyEvent;                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   OutFailReason_OnModifierApplyEvent;                // 0x0008(0x0010)(Parm, OutParm)
	bool                                          ReturnValue_OnModifierApplyEvent;                  // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_SubLayerModifier_C_OnModifierApplyEvent;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
