#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SubLayerModifier

#include "Basic.hpp"

#include "AvalancheSequence_structs.hpp"
#include "ActorModifierCore_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SubLayerModifier.BP_SubLayerModifier_C
// 0x0010 (0x00D0 - 0x00C0)
class UBP_SubLayerModifier_C final : public UActorModifierCoreBlueprintBase
{
public:
	struct FAvaSequenceName                       Change_In;                                         // 0x00C0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FAvaSequenceName                       Change_Out;                                        // 0x00C8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void OnModifierSetupEvent(struct FActorModifierCoreMetadata& InMetaData_OnModifierSetupEvent, struct FActorModifierCoreMetadata* OutMetadata_OnModifierSetupEvent);
	bool OnModifierApplyEvent(class AActor* InTargetActor_OnModifierApplyEvent, class FText* OutFailReason_OnModifierApplyEvent);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SubLayerModifier_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SubLayerModifier_C")
	}
	static class UBP_SubLayerModifier_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SubLayerModifier_C>();
	}
};
DUMPER7_ASSERTS_UBP_SubLayerModifier_C;

SDK_NAMESPACE_END
