#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SubLayerModifier

#include "Basic.hpp"

#include "BP_SubLayerModifier_classes.hpp"
#include "BP_SubLayerModifier_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_SubLayerModifier.BP_SubLayerModifier_C.OnModifierSetupEvent
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FActorModifierCoreMetadata&      InMetaData_OnModifierSetupEvent                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FActorModifierCoreMetadata*      OutMetadata_OnModifierSetupEvent                       (Parm, OutParm)

void UBP_SubLayerModifier_C::OnModifierSetupEvent(struct FActorModifierCoreMetadata& InMetaData_OnModifierSetupEvent, struct FActorModifierCoreMetadata* OutMetadata_OnModifierSetupEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SubLayerModifier_C", "OnModifierSetupEvent");

	Params::BP_SubLayerModifier_C_OnModifierSetupEvent Parms{};

	Parms.InMetaData_OnModifierSetupEvent = std::move(InMetaData_OnModifierSetupEvent);

	UObject::ProcessEvent(Func, &Parms);

	InMetaData_OnModifierSetupEvent = std::move(Parms.InMetaData_OnModifierSetupEvent);

	if (OutMetadata_OnModifierSetupEvent != nullptr)
		*OutMetadata_OnModifierSetupEvent = std::move(Parms.OutMetadata_OnModifierSetupEvent);
}


// Function BP_SubLayerModifier.BP_SubLayerModifier_C.OnModifierApplyEvent
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InTargetActor_OnModifierApplyEvent                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FText*                            OutFailReason_OnModifierApplyEvent                     (Parm, OutParm)
// bool                                    ReturnValue_OnModifierApplyEvent                       (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBP_SubLayerModifier_C::OnModifierApplyEvent(class AActor* InTargetActor_OnModifierApplyEvent, class FText* OutFailReason_OnModifierApplyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SubLayerModifier_C", "OnModifierApplyEvent");

	Params::BP_SubLayerModifier_C_OnModifierApplyEvent Parms{};

	Parms.InTargetActor_OnModifierApplyEvent = InTargetActor_OnModifierApplyEvent;

	UObject::ProcessEvent(Func, &Parms);

	if (OutFailReason_OnModifierApplyEvent != nullptr)
		*OutFailReason_OnModifierApplyEvent = std::move(Parms.OutFailReason_OnModifierApplyEvent);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
