#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SubLayerChangeTask

#include "Basic.hpp"

#include "BP_SubLayerChangeTask_classes.hpp"
#include "BP_SubLayerChangeTask_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_SubLayerChangeTask.BP_SubLayerChangeTask_C.Remove Inactive Players
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_SubLayerChangeTask_C::Remove_Inactive_Players()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SubLayerChangeTask_C", "Remove Inactive Players");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SubLayerChangeTask.BP_SubLayerChangeTask_C.ReceiveLatentTick
// (Event, Public, BlueprintEvent)
// Parameters:
// const float                             DeltaTime_ReceiveLatentTick                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SubLayerChangeTask_C::ReceiveLatentTick(const float DeltaTime_ReceiveLatentTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SubLayerChangeTask_C", "ReceiveLatentTick");

	Params::BP_SubLayerChangeTask_C_ReceiveLatentTick Parms{};

	Parms.DeltaTime_ReceiveLatentTick = DeltaTime_ReceiveLatentTick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SubLayerChangeTask.BP_SubLayerChangeTask_C.ReceiveLatentEnterState
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FStateTreeTransitionResult&Transition_ReceiveLatentEnterState                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_SubLayerChangeTask_C::ReceiveLatentEnterState(const struct FStateTreeTransitionResult& Transition_ReceiveLatentEnterState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SubLayerChangeTask_C", "ReceiveLatentEnterState");

	Params::BP_SubLayerChangeTask_C_ReceiveLatentEnterState Parms{};

	Parms.Transition_ReceiveLatentEnterState = std::move(Transition_ReceiveLatentEnterState);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SubLayerChangeTask.BP_SubLayerChangeTask_C.Process Controller
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TScriptInterface<class IAvaSequencePlaybackObject>Playback_Object                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class URCVirtualPropertyBase*           Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Succeed                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SubLayerChangeTask_C::Process_Controller(TScriptInterface<class IAvaSequencePlaybackObject> Playback_Object, class URCVirtualPropertyBase* Controller, bool* Succeed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SubLayerChangeTask_C", "Process Controller");

	Params::BP_SubLayerChangeTask_C_Process_Controller Parms{};

	Parms.Playback_Object = Playback_Object;
	Parms.Controller = Controller;

	UObject::ProcessEvent(Func, &Parms);

	if (Succeed != nullptr)
		*Succeed = Parms.Succeed;
}


// Function BP_SubLayerChangeTask.BP_SubLayerChangeTask_C.Process Changed Controllers
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_SubLayerChangeTask_C::Process_Changed_Controllers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SubLayerChangeTask_C", "Process Changed Controllers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SubLayerChangeTask.BP_SubLayerChangeTask_C.Find Sequence to Play for Actor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FAvaSequenceName                 ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FAvaSequenceName UBP_SubLayerChangeTask_C::Find_Sequence_to_Play_for_Actor(class AActor* Actor, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SubLayerChangeTask_C", "Find Sequence to Play for Actor");

	Params::BP_SubLayerChangeTask_C_Find_Sequence_to_Play_for_Actor Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;

	return Parms.ReturnValue;
}


// Function BP_SubLayerChangeTask.BP_SubLayerChangeTask_C.ExecuteUbergraph_BP_SubLayerChangeTask
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SubLayerChangeTask_C::ExecuteUbergraph_BP_SubLayerChangeTask(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SubLayerChangeTask_C", "ExecuteUbergraph_BP_SubLayerChangeTask");

	Params::BP_SubLayerChangeTask_C_ExecuteUbergraph_BP_SubLayerChangeTask Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
