#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CDE_MenuCameras

#include "Basic.hpp"

#include "CDE_MenuCameras_classes.hpp"
#include "CDE_MenuCameras_parameters.hpp"


SDK_NAMESPACE_START

// Function CDE_MenuCameras.CDE_MenuCameras_C.RunCameraDirector
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime_RunCameraDirector                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          EvaluationContextOwner_RunCameraDirector               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FBlueprintCameraDirectorEvaluationParams&Params_RunCameraDirector                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UCDE_MenuCameras_C::RunCameraDirector(float DeltaTime_RunCameraDirector, class UObject* EvaluationContextOwner_RunCameraDirector, const struct FBlueprintCameraDirectorEvaluationParams& Params_RunCameraDirector)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CDE_MenuCameras_C", "RunCameraDirector");

	Params::CDE_MenuCameras_C_RunCameraDirector Parms{};

	Parms.DeltaTime_RunCameraDirector = DeltaTime_RunCameraDirector;
	Parms.EvaluationContextOwner_RunCameraDirector = EvaluationContextOwner_RunCameraDirector;
	Parms.Params_RunCameraDirector = std::move(Params_RunCameraDirector);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CDE_MenuCameras.CDE_MenuCameras_C.ExecuteUbergraph_CDE_MenuCameras
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCDE_MenuCameras_C::ExecuteUbergraph_CDE_MenuCameras(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CDE_MenuCameras_C", "ExecuteUbergraph_CDE_MenuCameras");

	Params::CDE_MenuCameras_C_ExecuteUbergraph_CDE_MenuCameras Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
