#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CDE_MenuCameras

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayCameras_classes.hpp"
#include "E_MenuCameraRig_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CDE_MenuCameras.CDE_MenuCameras_C
// 0x0008 (0x0150 - 0x0148)
class UCDE_MenuCameras_C final : public UBlueprintCameraDirectorEvaluator
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0148(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void RunCameraDirector(float DeltaTime_RunCameraDirector, class UObject* EvaluationContextOwner_RunCameraDirector, const struct FBlueprintCameraDirectorEvaluationParams& Params_RunCameraDirector);
	void ExecuteUbergraph_CDE_MenuCameras(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CDE_MenuCameras_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CDE_MenuCameras_C")
	}
	static class UCDE_MenuCameras_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCDE_MenuCameras_C>();
	}
};
DUMPER7_ASSERTS_UCDE_MenuCameras_C;

SDK_NAMESPACE_END
