#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu

#include "Basic.hpp"

#include "MainMenu_classes.hpp"
#include "MainMenu_parameters.hpp"


SDK_NAMESPACE_START

// Function MainMenu.MainMenu_C.ShowErrorAndLogout
// (BlueprintCallable, BlueprintEvent)

void AMainMenu_C::ShowErrorAndLogout()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "ShowErrorAndLogout");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason_ReceiveEndPlay                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::ReceiveEndPlay(EEndPlayReason EndPlayReason_ReceiveEndPlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "ReceiveEndPlay");

	Params::MainMenu_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason_ReceiveEndPlay = EndPlayReason_ReceiveEndPlay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AMainMenu_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenu.MainMenu_C.OnResult_D34857C845D37E0D0A72BE8DBC3FF223
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ETyrMessagingResult                     Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::OnResult_D34857C845D37E0D0A72BE8DBC3FF223(ETyrMessagingResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnResult_D34857C845D37E0D0A72BE8DBC3FF223");

	Params::MainMenu_C_OnResult_D34857C845D37E0D0A72BE8DBC3FF223 Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.OnResult_7373D25F4E8B0FC8574F4D83F4263575
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ETyrMessagingResult                     Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::OnResult_7373D25F4E8B0FC8574F4D83F4263575(ETyrMessagingResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnResult_7373D25F4E8B0FC8574F4D83F4263575");

	Params::MainMenu_C_OnResult_7373D25F4E8B0FC8574F4D83F4263575 Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.OnResult_65EDA7D04846156E0E40008F8D27AB91
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ETyrMessagingResult                     Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::OnResult_65EDA7D04846156E0E40008F8D27AB91(ETyrMessagingResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnResult_65EDA7D04846156E0E40008F8D27AB91");

	Params::MainMenu_C_OnResult_65EDA7D04846156E0E40008F8D27AB91 Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.OnMessageReceived_E97DE56541B99602322CFDB4CEBB29F2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::OnMessageReceived_E97DE56541B99602322CFDB4CEBB29F2(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnMessageReceived_E97DE56541B99602322CFDB4CEBB29F2");

	Params::MainMenu_C_OnMessageReceived_E97DE56541B99602322CFDB4CEBB29F2 Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.OnMessageReceived_A80A3D62451987E1ADD8758DA446983C
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAsyncAction_ListenForGameplayMessage*ProxyObject                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ActualChannel                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::OnMessageReceived_A80A3D62451987E1ADD8758DA446983C(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "OnMessageReceived_A80A3D62451987E1ADD8758DA446983C");

	Params::MainMenu_C_OnMessageReceived_A80A3D62451987E1ADD8758DA446983C Parms{};

	Parms.ProxyObject = ProxyObject;
	Parms.ActualChannel = std::move(ActualChannel);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.ExecuteUbergraph_MainMenu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::ExecuteUbergraph_MainMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "ExecuteUbergraph_MainMenu");

	Params::MainMenu_C_ExecuteUbergraph_MainMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.BeforePush_7EECB6394A80FF74D4969B84EFCB4468
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatableWidget*         UserWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::BeforePush_7EECB6394A80FF74D4969B84EFCB4468(class UCommonActivatableWidget* UserWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "BeforePush_7EECB6394A80FF74D4969B84EFCB4468");

	Params::MainMenu_C_BeforePush_7EECB6394A80FF74D4969B84EFCB4468 Parms{};

	Parms.UserWidget = UserWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenu.MainMenu_C.AfterPush_7EECB6394A80FF74D4969B84EFCB4468
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatableWidget*         UserWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void AMainMenu_C::AfterPush_7EECB6394A80FF74D4969B84EFCB4468(class UCommonActivatableWidget* UserWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenu_C", "AfterPush_7EECB6394A80FF74D4969B84EFCB4468");

	Params::MainMenu_C_AfterPush_7EECB6394A80FF74D4969B84EFCB4468 Parms{};

	Parms.UserWidget = UserWidget;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
