#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu

#include "Basic.hpp"

#include "Tyr_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function MainMenu.MainMenu_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct MainMenu_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason_ReceiveEndPlay;                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MainMenu_C_ReceiveEndPlay;

// Function MainMenu.MainMenu_C.OnResult_D34857C845D37E0D0A72BE8DBC3FF223
// 0x0001 (0x0001 - 0x0000)
struct MainMenu_C_OnResult_D34857C845D37E0D0A72BE8DBC3FF223 final
{
public:
	ETyrMessagingResult                           Result;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MainMenu_C_OnResult_D34857C845D37E0D0A72BE8DBC3FF223;

// Function MainMenu.MainMenu_C.OnResult_7373D25F4E8B0FC8574F4D83F4263575
// 0x0001 (0x0001 - 0x0000)
struct MainMenu_C_OnResult_7373D25F4E8B0FC8574F4D83F4263575 final
{
public:
	ETyrMessagingResult                           Result;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MainMenu_C_OnResult_7373D25F4E8B0FC8574F4D83F4263575;

// Function MainMenu.MainMenu_C.OnResult_65EDA7D04846156E0E40008F8D27AB91
// 0x0001 (0x0001 - 0x0000)
struct MainMenu_C_OnResult_65EDA7D04846156E0E40008F8D27AB91 final
{
public:
	ETyrMessagingResult                           Result;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MainMenu_C_OnResult_65EDA7D04846156E0E40008F8D27AB91;

// Function MainMenu.MainMenu_C.OnMessageReceived_E97DE56541B99602322CFDB4CEBB29F2
// 0x0010 (0x0010 - 0x0000)
struct MainMenu_C_OnMessageReceived_E97DE56541B99602322CFDB4CEBB29F2 final
{
public:
	class UAsyncAction_ListenForGameplayMessage*  ProxyObject;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           ActualChannel;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MainMenu_C_OnMessageReceived_E97DE56541B99602322CFDB4CEBB29F2;

// Function MainMenu.MainMenu_C.OnMessageReceived_A80A3D62451987E1ADD8758DA446983C
// 0x0010 (0x0010 - 0x0000)
struct MainMenu_C_OnMessageReceived_A80A3D62451987E1ADD8758DA446983C final
{
public:
	class UAsyncAction_ListenForGameplayMessage*  ProxyObject;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           ActualChannel;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MainMenu_C_OnMessageReceived_A80A3D62451987E1ADD8758DA446983C;

// Function MainMenu.MainMenu_C.ExecuteUbergraph_MainMenu
// 0x0350 (0x0350 - 0x0000)
struct MainMenu_C_ExecuteUbergraph_MainMenu final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonActivatableWidget*               K2Node_CustomEvent_UserWidget;                     // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAsyncAction_ListenForGameplayMessage*  K2Node_CustomEvent_ProxyObject_1;                  // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_CustomEvent_ActualChannel_1;                // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FTyrAuthBannedMessage                  Temp_struct_Variable;                              // 0x0020(0x0008)(NoDestructor)
	struct FGameplayTag                           Temp_struct_Variable_1;                            // 0x0028(0x0008)(NoDestructor, HasGetValueTypeHash)
	class UAsyncAction_ListenForGameplayMessage*  Temp_object_Variable;                              // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAsyncAction_ListenForGameplayMessage*  CallFunc_ListenForGameplayMessages_ReturnValue;    // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTyrAuthSuspendedMessage               Temp_struct_Variable_2;                            // 0x0040(0x0010)(NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAsyncAction_ListenForGameplayMessage*  K2Node_CustomEvent_ProxyObject;                    // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           K2Node_CustomEvent_ActualChannel;                  // 0x0060(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)> K2Node_CreateDelegate_OutputDelegate; // 0x0068(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTyrAuthSuspendedMessage               Temp_struct_Variable_3;                            // 0x0078(0x0010)(NoDestructor)
	struct FGameplayTag                           Temp_struct_Variable_4;                            // 0x0088(0x0008)(NoDestructor, HasGetValueTypeHash)
	class UAsyncAction_ListenForGameplayMessage*  Temp_object_Variable_1;                            // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAsyncAction_ListenForGameplayMessage*  CallFunc_ListenForGameplayMessages_ReturnValue_1;  // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetPayload_ReturnValue;                   // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A2[0x6];                                       // 0x00A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTyrOnlineSubsystem*                    CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ETyrMessagingResult Result)>   K2Node_CreateDelegate_OutputDelegate_1;            // 0x00B0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TryToLogOutUser_ReturnValue;              // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UTyrOnlineUserInfo*               CallFunc_GetUserInfoForLocalPlayerIndex_ReturnValue; // 0x00C8(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ETyrMessagingResult                           K2Node_CustomEvent_Result;                         // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTyrOnlineErrorWrapper                 CallFunc_HasErrorRequiringLogout_Error;            // 0x00D8(0x0028)()
	bool                                          CallFunc_HasErrorRequiringLogout_ReturnValue;      // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETyrMessagingResult                           Temp_byte_Variable;                                // 0x0101(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_102[0x6];                                      // 0x0102(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTyrAsyncActionShowError*               CallFunc_ShowErrorOkWithError_ReturnValue;         // 0x0108(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTyrOnlineSubsystem*                    CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	const class UTyrOnlineUserInfo*               CallFunc_GetUserInfoForLocalPlayerIndex_ReturnValue_1; // 0x0118(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTyrOnlineErrorWrapper                 CallFunc_HasErrorRequiringLogout_Error_1;          // 0x0120(0x0028)()
	bool                                          CallFunc_HasErrorRequiringLogout_ReturnValue_1;    // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14A[0x6];                                      // 0x014A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTyrGameUpdateSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue_2;   // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTyrOnlineSubsystem*                    CallFunc_GetGameInstanceSubsystem_ReturnValue_3;   // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0160(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocalPlayerController_ReturnValue;      // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_169[0x3];                                      // 0x0169(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UCommonActivatableWidget* UserWidget)> K2Node_CreateDelegate_OutputDelegate_2; // 0x016C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x017C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17D[0x3];                                      // 0x017D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0180(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x0188(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTyrPlayerMatchSubsystem*               CallFunc_GetLocalPlayerSubSystemFromPlayerController_ReturnValue; // 0x0190(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTyrAsyncActionPushContentToLayerForPlayer* CallFunc_PushContentToLayerForPlayer_ReturnValue; // 0x0198(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasLastMatchDetailsId_ReturnValue;        // 0x01A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A2[0x6];                                      // 0x01A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x01A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_GameInstanceBase_C*                 K2Node_DynamicCast_AsBP_Game_Instance_Base;        // 0x01B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B9[0x7];                                      // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_3;        // 0x01C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULocalPlayer*                           CallFunc_GetLocalPlayerFromController_ReturnValue; // 0x01C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTyrLocalPlayer*                        K2Node_DynamicCast_AsTyr_Local_Player;             // 0x01D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D9[0x3];                                      // 0x01D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UAsyncAction_ListenForGameplayMessage* ProxyObject, const struct FGameplayTag& ActualChannel)> K2Node_CreateDelegate_OutputDelegate_3; // 0x01DC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1EC[0x4];                                      // 0x01EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTyrSettingsLocal*                      CallFunc_GetLocalSettings_ReturnValue;             // 0x01F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_1;            // 0x01F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_GameInstanceBase_C*                 K2Node_DynamicCast_AsBP_Game_Instance_Base_1;      // 0x0200(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_209[0x7];                                      // 0x0209(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0210(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_QuartzClock_C*                      CallFunc_FinishSpawningActor_ReturnValue;          // 0x0218(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IAudioParameterControllerInterface> CallFunc_SetTriggerParameter_self_CastInput; // 0x0220(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0231(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsClockRunning_ReturnValue;               // 0x0232(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_233[0x5];                                      // 0x0233(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonActivatableWidget*               K2Node_CustomEvent_UserWidget_1;                   // 0x0238(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_241[0x3];                                      // 0x0241(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UCommonActivatableWidget* UserWidget)> K2Node_CreateDelegate_OutputDelegate_4; // 0x0244(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_254[0x4];                                      // 0x0254(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue_2;            // 0x0258(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTyrGameInstance*                       K2Node_DynamicCast_AsTyr_Game_Instance;            // 0x0260(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTyrAuthBannedMessage                  Temp_struct_Variable_5;                            // 0x0270(0x0008)(NoDestructor)
	bool                                          CallFunc_GetPayload_ReturnValue_1;                 // 0x0278(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x0279(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETyrMessagingResult                           Temp_byte_Variable_1;                              // 0x027A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETyrMessagingResult                           K2Node_CustomEvent_Result_1;                       // 0x027B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ETyrMessagingResult Result)>   K2Node_CreateDelegate_OutputDelegate_5;            // 0x027C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_28C[0x4];                                      // 0x028C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTyrGameUIManagerSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue_4;   // 0x0290(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ETyrMessagingResult                           Temp_byte_Variable_2;                              // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299[0x7];                                      // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTyrOnlineErrorWrapper                 CallFunc_ShowReturnToMainMenuError_OutError;       // 0x02A0(0x0028)()
	bool                                          CallFunc_ShowReturnToMainMenuError_ReturnValue;    // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C9[0x7];                                      // 0x02C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTyrAsyncActionShowError*               CallFunc_ShowErrorOkWithError_ReturnValue_1;       // 0x02D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D9[0x7];                                      // 0x02D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_4;        // 0x02E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULocalPlayer*                           CallFunc_GetLocalPlayerFromController_ReturnValue_1; // 0x02E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ETyrMessagingResult                           K2Node_CustomEvent_Result_2;                       // 0x02F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F1[0x7];                                      // 0x02F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_Notification_C*                    CallFunc_PushNotificationToQueue_ReturnValue;      // 0x02F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTyrGameUIManagerSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue_5;   // 0x0300(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(ETyrMessagingResult Result)>   K2Node_CreateDelegate_OutputDelegate_6;            // 0x0308(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_ShowReturnToMainMenuReason_OutReason;     // 0x0318(0x0010)()
	ETyrShowReturnMessageResult                   CallFunc_ShowReturnToMainMenuReason_ReturnValue;   // 0x0328(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_329[0x7];                                      // 0x0329(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonActivatableWidget*               Temp_object_Variable_2;                            // 0x0330(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0338(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_339[0x7];                                      // 0x0339(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTyrAsyncActionShowConfirmation*        CallFunc_ShowConfirmationOk_ReturnValue;           // 0x0340(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x0348(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MainMenu_C_ExecuteUbergraph_MainMenu;

// Function MainMenu.MainMenu_C.BeforePush_7EECB6394A80FF74D4969B84EFCB4468
// 0x0008 (0x0008 - 0x0000)
struct MainMenu_C_BeforePush_7EECB6394A80FF74D4969B84EFCB4468 final
{
public:
	class UCommonActivatableWidget*               UserWidget;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MainMenu_C_BeforePush_7EECB6394A80FF74D4969B84EFCB4468;

// Function MainMenu.MainMenu_C.AfterPush_7EECB6394A80FF74D4969B84EFCB4468
// 0x0008 (0x0008 - 0x0000)
struct MainMenu_C_AfterPush_7EECB6394A80FF74D4969B84EFCB4468 final
{
public:
	class UCommonActivatableWidget*               UserWidget;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_MainMenu_C_AfterPush_7EECB6394A80FF74D4969B84EFCB4468;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
