#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC_MainMenu

#include "Basic.hpp"

#include "Tyr_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PC_MainMenu.PC_MainMenu_C
// 0x0008 (0x0750 - 0x0748)
class APC_MainMenu_C final : public ATyrCommonPlayerController
{
public:
	class UGameplayCameraComponent*               GameplayCamera;                                    // 0x0748(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PC_MainMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PC_MainMenu_C")
	}
	static class APC_MainMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APC_MainMenu_C>();
	}
};
DUMPER7_ASSERTS_APC_MainMenu_C;

SDK_NAMESPACE_END
